# Generated by Django 3.2.4 on 2021-11-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='destroy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secret',
            name='user_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
