# Generated by Django 3.2.4 on 2021-11-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0005_auto_20211120_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
