# Generated by Django 3.2.4 on 2021-11-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_alter_secret_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='destroy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='user_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
