# Generated by Django 3.2.4 on 2021-11-20 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passwords', '0007_auto_20211120_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='user_id',
        ),
        migrations.AddField(
            model_name='secret',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', null=True, blank=True),
            preserve_default=False,
        ),
    ]
